version: "3.8"
services:
  cervantes-db:
    container_name: cervantes-db
    networks:
      - cervantes
    image: mesq/cervantes-postgres:dev
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      POSTGRES_DB: cervantes
      POSTGRES_USER: cervantes
      POSTGRES_PASSWORD: CervantesDBTjakra

  cervantes-app:
    container_name: cervantes-app
    networks:
      - cervantes
    image: aldovadev/pemda-tjakra:latest
    depends_on:
      - cervantes-db
    restart: unless-stopped
    ports:
      - "10083:80"
      - "10443:443"

networks:
  cervantes:
    driver: bridge
